# Generated by Django 4.0.6 on 2022-08-15 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Last_modify', models.DateField(auto_now=True)),
            ],
        ),
    ]
