# Generated by Django 4.0.6 on 2022-08-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='department',
            field=models.CharField(default='未設置', max_length=30),
        ),
    ]
