# Generated by Django 4.0.6 on 2022-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0004_news_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
