# Generated by Django 4.0.6 on 2022-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
            ],
        ),
    ]
