# Generated by Django 4.0.6 on 2022-08-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='account',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
    ]
